In [2]:
%%html
<!--마그다운 표 정렬 설정-->
<style> table(float:left) </style>

## 06-1 데이터 전처리 - 원하는 형태로 데이터 가공하기
|함수      |기능         |
|---------|-------------|
| query()   | 행 추출 |
| df[]  | 열(변수)추출 |
| sort_values() | 정렬|
| groupby() | 집단별로 나누기|
| agg() | 통계치 구하기 |
| merge() | 데이터 합치기(열)|
| concat() | 데이터 합치기(행)|

In [5]:
# 판다스 불러오기
import pandas as pd
import numpy as np
exam = pd.read_csv('exam.csv')
exam.head()

   id  nclass  math  english  science
0   1       1    50       98       50
1   2       1    60       97       60
2   3       1    45       86       78
3   4       1    30       98       58
4   5       2    25       80       65

In [6]:
# exam nclass가 1인 경우인 추출
exam.query('nclass ==1')

   id  nclass  math  english  science
0   1       1    50       98       50
1   2       1    60       97       60
2   3       1    45       86       78
3   4       1    30       98       58

In [7]:
# exam nclass가 2인 경우인 추출
exam.query('nclass ==2')

   id  nclass  math  english  science
4   5       2    25       80       65
5   6       2    50       89       98
6   7       2    80       90       45
7   8       2    90       78       25

In [8]:
# exam.nclass가 3인 경우인 추출
exam.query('nclass ==3')

    id  nclass  math  english  science
8    9       3    20       98       15
9   10       3    50       98       45
10  11       3    65       65       65
11  12       3    45       85       32

In [10]:
# exam.nclass가 4인 경우인 추출
exam.query('nclass ==4')

    id  nclass  math  english  science
12  13       4    46       98       65
13  14       4    48       87       12
14  15       4    75       56       78
15  16       4    58       98       65

In [11]:
# exam.nclass가 5인 경우인 추출
exam.query('nclass ==5')

    id  nclass  math  english  science
16  17       5    65       68       98
17  18       5    80       78       90
18  19       5    89       68       87
19  20       5    78       83       58

In [20]:
# 문제 수학점수가 50점 초과한 경우
exam.query('math >= 50')

    id  nclass  math  english  science
0    1       1    50       98       50
1    2       1    60       97       60
5    6       2    50       89       98
6    7       2    80       90       45
7    8       2    90       78       25
9   10       3    50       98       45
10  11       3    65       65       65
14  15       4    75       56       78
15  16       4    58       98       65
16  17       5    65       68       98
17  18       5    80       78       90
18  19       5    89       68       87
19  20       5    78       83       58

In [21]:
# 1반이면서 수학점수가 50점 이상인 경우 추출
exam.query('nclass == 1 & math >= 50')

   id  nclass  math  english  science
0   1       1    50       98       50
1   2       1    60       97       60

In [22]:
# 2반이면서 영어점수가 80점 이상인 경우
exam.query('nclass == 2 & english >= 80')

   id  nclass  math  english  science
4   5       2    25       80       65
5   6       2    50       89       98
6   7       2    80       90       45

In [23]:
# 수학점수가 90점 이상이거나 영어 점수가 90점 이상인 경우
exam.query('math >= 90 | english >= 90')

    id  nclass  math  english  science
0    1       1    50       98       50
1    2       1    60       97       60
3    4       1    30       98       58
6    7       2    80       90       45
7    8       2    90       78       25
8    9       3    20       98       15
9   10       3    50       98       45
12  13       4    46       98       65
15  16       4    58       98       65

In [27]:
# 영어 점수가 90점 미만이거나 과학 점수가 50점 미만인 경우
exam.query('english < 90 | science < 50')

    id  nclass  math  english  science
2    3       1    45       86       78
4    5       2    25       80       65
5    6       2    50       89       98
6    7       2    80       90       45
7    8       2    90       78       25
8    9       3    20       98       15
9   10       3    50       98       45
10  11       3    65       65       65
11  12       3    45       85       32
13  14       4    48       87       12
14  15       4    75       56       78
16  17       5    65       68       98
17  18       5    80       78       90
18  19       5    89       68       87
19  20       5    78       83       58

In [31]:
# 1,3,5반에 해당하는 값 출력
# exam.query('nclass == 1 | nclass == 3 | nclass == 5')
exam.query('nclass in[1,3,5]')

    id  nclass  math  english  science
0    1       1    50       98       50
1    2       1    60       97       60
2    3       1    45       86       78
3    4       1    30       98       58
8    9       3    20       98       15
9   10       3    50       98       45
10  11       3    65       65       65
11  12       3    45       85       32
16  17       5    65       68       98
17  18       5    80       78       90
18  19       5    89       68       87
19  20       5    78       83       58

In [32]:
# nclass가 1인 행을 추출해서 nclass1 할당
nclass1 = exam.query('nclass == 1')
# nclass가 2인 행 추출해서 nclass2 할당
nclass2 = exam.query('nclass == 2')

In [34]:
# 1반 수학 점수 평균
nclass1['math'].mean()

46.25

In [35]:
# 2반 수학 점수 평균
nclass2['math'].mean()

61.25

In [36]:
nclass1['english'].mean()

94.75

In [40]:
nclass2['english'].mean()

84.25

In [43]:
df = pd.DataFrame({'sex' : ['F','M','F','M'],
                  'country' : ['Korea','China','Japan','USA']})
df

  sex country
0   F   Korea
1   M   China
2   F   Japan
3   M     USA

In [44]:
# 여자이면서 한국인 데이터 추출 and = 이면서 or = 이거나
# 전체 조건 작은따옴표, 추출할 문자에는 큰따옴표 사용
df.query('sex == "F"& country == "korea"')

Empty DataFrame
Columns: [sex, country]
Index: []

In [45]:
# 남자이면서 중국인 데이터 추출
df.query("sex =='M' & country == 'China'")

  sex country
1   M   China

In [48]:
var = int(input('반을 입력하세요 : '))
exam.query('nclass == @var')

반을 입력하세요 : 2

   id  nclass  math  english  science
4   5       2    25       80       65
5   6       2    50       89       98
6   7       2    80       90       45
7   8       2    90       78       25

| 논리 연산자 | 기능    |
|:----------:|-----------|
| <       | 작다       |
| <=       | 작거나 크다   |
| >       | 크다        |
| < = | 크거나 같다    |
| ==    | 같다        |
| !=       | 같지 않다|
| \|             | 또는  |
| &      | 그리고   |
| in     | 매칭 확인  |

| 산술 연산자 | 기능    |
|:----------:|-----------|
| +       | 더하기       |
| -       | 빼기 |
| *       | 곱하기  |
| ** | 제곱    |
| /    | 나누기        |
| //      | 나눗셈의 몫|
| %             | 나눗셈의 나머지 |

In [51]:
# 변수 추출하기
exam['math']

0     50
1     60
2     45
3     30
4     25
5     50
6     80
7     90
8     20
9     50
10    65
11    45
12    46
13    48
14    75
15    58
16    65
17    80
18    89
19    78
Name: math, dtype: int64

In [58]:
# 여러개의 변수 추출
# exam[['nclass','math','english','science']]
exam.drop(columns = ['id','nclass'])

    math  english  science
0     50       98       50
1     60       97       60
2     45       86       78
3     30       98       58
4     25       80       65
5     50       89       98
6     80       90       45
7     90       78       25
8     20       98       15
9     50       98       45
10    65       65       65
11    45       85       32
12    46       98       65
13    48       87       12
14    75       56       78
15    58       98       65
16    65       68       98
17    80       78       90
18    89       68       87
19    78       83       58

In [59]:
# nclass가 1인 행만 추출한 다음 english 추출
exam.query('nclass==1')['english']

0    98
1    97
2    86
3    98
Name: english, dtype: int64

In [60]:
# math가 50 이상인 행만 추출한 다음 id,math 추출
exam.query('math >= 50')[['id','math']]

    id  math
0    1    50
1    2    60
5    6    50
6    7    80
7    8    90
9   10    50
10  11    65
14  15    75
15  16    58
16  17    65
17  18    80
18  19    89
19  20    78