In [18]:
%%html
<!--마크다운 표 정렬 설정-->
<style> table {float:left} </style>

## 데이터 전처리 - 원하는 형태로 데이터 가공하기

| 함수 | 기능    |
|---------|----------|
| query()     | 행 추출  |
| df[]      | 열(변수) 추출 |
| sort_values() | 정렬    |
| groupby() | 집단별로 나누기 |
| agg()   | 통계치 구하기
| merge()   | 데이터 합치기(열) |
| concat()  | 데이터 합치기(행) |

In [12]:
# 라이브러리 불러오기
import pandas as pd
import numpy as np
exam = pd.read_csv('exam.csv')
exam.head()

   id  nclass  math  english  science
0   1       1    50       98       50
1   2       1    60       97       60
2   3       1    45       86       78
3   4       1    30       98       58
4   5       2    25       80       65

In [13]:
# exam에서 nclass가 3인 경우만 추출
exam.query('nclass == 3')

    id  nclass  math  english  science
8    9       3    20       98       15
9   10       3    50       98       45
10  11       3    65       65       65
11  12       3    45       85       32

In [14]:
# exam에서 nclass가 3반이 아닌 경우만 추출
exam.query('nclass != 3')

    id  nclass  math  english  science
0    1       1    50       98       50
1    2       1    60       97       60
2    3       1    45       86       78
3    4       1    30       98       58
4    5       2    25       80       65
5    6       2    50       89       98
6    7       2    80       90       45
7    8       2    90       78       25
12  13       4    46       98       65
13  14       4    48       87       12
14  15       4    75       56       78
15  16       4    58       98       65
16  17       5    65       68       98
17  18       5    80       78       90
18  19       5    89       68       87
19  20       5    78       83       58

In [17]:
# 초과 미만 이상 이하
# >    <    >=   <=
# 수학점수가 50점 초과한 경우 추출
exam.query('math > 50')

    id  nclass  math  english  science
1    2       1    60       97       60
6    7       2    80       90       45
7    8       2    90       78       25
10  11       3    65       65       65
14  15       4    75       56       78
15  16       4    58       98       65
16  17       5    65       68       98
17  18       5    80       78       90
18  19       5    89       68       87
19  20       5    78       83       58

In [19]:
# 여러 조건을 충족하는 행 추출하기
# 이거나 Or |
# 이면서 And &

In [22]:
# 1반 이면서 수학점수가 50점 이상인 경우
# nClass == 1
# 이면서 &
# math >= 50

exam.query('nclass ==1 & math>=50')

   id  nclass  math  english  science
0   1       1    50       98       50
1   2       1    60       97       60

In [23]:
# 문제 모든 과목이 50점 이상인 경우 추출
# 모든 과목 And &
# math >= 50
# science >= 50
exam.query('math >= 50 & english >= 50 & science >= 50')

    id  nclass  math  english  science
0    1       1    50       98       50
1    2       1    60       97       60
5    6       2    50       89       98
10  11       3    65       65       65
14  15       4    75       56       78
15  16       4    58       98       65
16  17       5    65       68       98
17  18       5    80       78       90
18  19       5    89       68       87
19  20       5    78       83       58

In [25]:
# 모든 과목중에 한과목이라도 90점이 넘는 과목의 경우 추출
exam.query('math >= 95 | english >= 95 | science >= 95')

    id  nclass  math  english  science
0    1       1    50       98       50
1    2       1    60       97       60
3    4       1    30       98       58
5    6       2    50       89       98
8    9       3    20       98       15
9   10       3    50       98       45
12  13       4    46       98       65
15  16       4    58       98       65
16  17       5    65       68       98

In [27]:
# 추출한 행으로 데이터 만들기

nclass1 = exam.query('nclass==1')

In [28]:
nclass1['math'].mean()

46.25

In [33]:
# 원하는 열만 출력할 경우
exam[['nclass','math','english']].head()

   nclass  math  english
0       1    50       98
1       1    60       97
2       1    45       86
3       1    30       98
4       2    25       80

In [35]:
# 원하는 열을 제거하고 출력할 경우
# 메소드 .drop
# math 제거하고 출력
exam.drop(columns = 'math').head()

   id  nclass  english  science
0   1       1       98       50
1   2       1       97       60
2   3       1       86       78
3   4       1       98       58
4   5       2       80       65

In [39]:
# query + [] 조합 검색
# nclass가 1 이고 영어만 출력
exam.query('nclass==1')[['english']]

   english
0       98
1       97
2       86
3       98

In [42]:
# math 50점 이상인 행에서 id math 추출
exam.query('math >= 50')[['id','math']].head()

   id  math
0   1    50
1   2    60
5   6    50
6   7    80
7   8    90

In [43]:
# 오름차순으로 정렬하기 .sort_values()
# 수학점수로 정렬
exam.sort_values('math').head()

    id  nclass  math  english  science
8    9       3    20       98       15
4    5       2    25       80       65
3    4       1    30       98       58
2    3       1    45       86       78
11  12       3    45       85       32

In [44]:
# 내림차순 속성 ascending = False
exam.sort_values('math',ascending = False).head()

    id  nclass  math  english  science
7    8       2    90       78       25
18  19       5    89       68       87
17  18       5    80       78       90
6    7       2    80       90       45
19  20       5    78       83       58

In [45]:
# nclass, math 오름차순
exam.sort_values(['nclass','math'])

    id  nclass  math  english  science
3    4       1    30       98       58
2    3       1    45       86       78
0    1       1    50       98       50
1    2       1    60       97       60
4    5       2    25       80       65
5    6       2    50       89       98
6    7       2    80       90       45
7    8       2    90       78       25
8    9       3    20       98       15
11  12       3    45       85       32
9   10       3    50       98       45
10  11       3    65       65       65
12  13       4    46       98       65
13  14       4    48       87       12
15  16       4    58       98       65
14  15       4    75       56       78
16  17       5    65       68       98
19  20       5    78       83       58
17  18       5    80       78       90
18  19       5    89       68       87

In [46]:
# nclass 내림차순 math 오름차순
exam.sort_values(['nclass','math'],ascending = [False,True]).head(10)

    id  nclass  math  english  science
16  17       5    65       68       98
19  20       5    78       83       58
17  18       5    80       78       90
18  19       5    89       68       87
12  13       4    46       98       65
13  14       4    48       87       12
15  16       4    58       98       65
14  15       4    75       56       78
8    9       3    20       98       15
11  12       3    45       85       32

In [49]:
# 변수 추가 .assign
# total
exam.assign(total = exam['math']+exam['english'] + exam['science']).head(10)

   id  nclass  math  english  science  total
0   1       1    50       98       50    198
1   2       1    60       97       60    217
2   3       1    45       86       78    209
3   4       1    30       98       58    186
4   5       2    25       80       65    170
5   6       2    50       89       98    237
6   7       2    80       90       45    215
7   8       2    90       78       25    193
8   9       3    20       98       15    133
9  10       3    50       98       45    193

In [53]:
exam.assign(total = exam['math']+exam['english']+exam['science'],
           mean =( exam['math']+exam['english']+exam['science'])/3) # total 추가

    id  nclass  math  english  science  total       mean
0    1       1    50       98       50    198  66.000000
1    2       1    60       97       60    217  72.333333
2    3       1    45       86       78    209  69.666667
3    4       1    30       98       58    186  62.000000
4    5       2    25       80       65    170  56.666667
5    6       2    50       89       98    237  79.000000
6    7       2    80       90       45    215  71.666667
7    8       2    90       78       25    193  64.333333
8    9       3    20       98       15    133  44.333333
9   10       3    50       98       45    193  64.333333
10  11       3    65       65       65    195  65.000000
11  12       3    45       85       32    162  54.000000
12  13       4    46       98       65    209  69.666667
13  14       4    48       87       12    147  49.000000
14  15       4    75       56       78    209  69.666667
15  16       4    58       98       65    221  73.666667
16  17       5    65       68       98    231  77.000000
17  18       5    80       78       90    248  82.666667
18  19       5    89       68       87    244  81.333333
19  20       5    78       83       58    219  73.000000

### df.assign()에 ### np,where() 적용하기

In [54]:
# test 열을 만들어 주고 과학이 60점 이상이면 pass fall
exam.assign(test = np.where(exam['science']>=60,'pass','fall'))

    id  nclass  math  english  science  test
0    1       1    50       98       50  fall
1    2       1    60       97       60  pass
2    3       1    45       86       78  pass
3    4       1    30       98       58  fall
4    5       2    25       80       65  pass
5    6       2    50       89       98  pass
6    7       2    80       90       45  fall
7    8       2    90       78       25  fall
8    9       3    20       98       15  fall
9   10       3    50       98       45  fall
10  11       3    65       65       65  pass
11  12       3    45       85       32  fall
12  13       4    46       98       65  pass
13  14       4    48       87       12  fall
14  15       4    75       56       78  pass
15  16       4    58       98       65  pass
16  17       5    65       68       98  pass
17  18       5    80       78       90  pass
18  19       5    89       68       87  pass
19  20       5    78       83       58  fall